wheeltec_imu_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    yaw_offset: -1.9363 

nmea_serial_driver:
  ros__parameters:
    port: "/dev/ttyACM1"

motor_driver:
  ros__parameters:
    serial_port: "/dev/ttyACM0"
    PWM_FULL: 1600
    PWM_NEUTRAL: 1580
    PWM_BRAKE: 1500
    FORWARD: 1

/**:
  navsat_transform_node:
    ros__parameters:
      magnetic_declination_radians: -0.04503
      yaw_offset: 0.0 
      zero_altitude: True
      use_odometry_yaw: True 
      wait_for_datum: False 
      publish_filtered_gps: True
      broadcast_cartesian_transform: False
  mpc_node:
    ros__parameters:
      max_speed: 1.0
      min_speed: 0.5
      horizon: 8
      dt: 0.3
      max_acceleration: 5.0
      wheelbase: 0.25
      max_steering_angle: 0.2
      control_smoothing: 0.9
      collision_distance: 3.0
      timer_frequency: 0.006


ublox_gps_node:
  ros__parameters:
    debug: 0                    
    device: /dev/ttyACM1
    tmode3: 0    
    config_on_startup: False


