wheeltec_imu_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
nmea_serial_driver:
  ros__parameters:
    port: "/dev/ttyACM0"
motor_driver:
  ros__parameters:
    serial_port: "/dev/ttyACM1"
    PWM_FULL: 1550
