wheeltec_imu_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    
nmea_serial_driver:
  ros__parameters:
    port: "/dev/ttyACM1"

motor_driver:
  ros__parameters:
    serial_port: "/dev/ttyACM0"
    PWM_FULL: 1550
    PWM_NEUTRAL: 1400
    PWM_BRAKE: 1400
    FORWARD: 1

/**:
  navsat_transform_node:
    ros__parameters:
      magnetic_declination_radians: -0.04503
      yaw_offset: 0.0 
      zero_altitude: True
      use_odometry_yaw: True 
      wait_for_datum: False 
      publish_filtered_gps: True
      broadcast_cartesian_transform: False

ublox_gps_node:
  ros__parameters:
    debug: 0                    
    device: /dev/ttyACM1
    tmode3: 0    
    config_on_startup: False
