wheeltec_imu_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"

nmea_serial_driver:
  ros__parameters:
    port: "/dev/ttyACM0"

motor_driver:
  ros__parameters:
    serial_port: "/dev/ttyACM1"
    PWM_FULL: 1400
    PWM_NEUTRAL: 1500
    PWM_BRAKE: 1600
    FORWARD: 1

/artcar_1/navsat_transform_node:
  ros__parameters:
    magnetic_declination_radians: -0.0524
    yaw_offset: -0.75
    zero_altitude: True
    use_odometry_yaw: True
    wait_for_datum: False
    publish_filtered_gps: True
    broadcast_cartesian_transform: False

