/**:
  navsat_transform_node:
    ros__parameters:
      magnetic_declination_radians: 0.0
      yaw_offset: 0.0
      zero_altitude: True
      use_odometry_yaw: True
      wait_for_datum: False 
      publish_filtered_gps: True
      broadcast_cartesian_transform: False
  velocity_controller:
    ros__parameters:
      velocity_kp: 2.0
      velocity_kd: 0.0
      velocity_ki: 0.0
      velocity_error_integral_limit: 1.0
      target_velocity: 0.08
  follower_control_node:
    ros__parameters:
      steering_kp: 4.3
      steering_ki: 0.1 
      steering_kd: -0.85
      steering_cte_integral_limit: 5.0
      predefined_path: True

  mpc_node:
    ros__parameters:
      max_speed: 1.0
      min_speed: 0.2
      horizon: 5
      dt: 0.6
      max_acceleration: 5.0
      wheelbase: 0.3
      max_steering_angle: 0.52
      control_smoothing: 0.25
      collision_distance: 3.0
      timer_frequency: 0.05

/**:
    ros__parameters:
      use_sim_time: true
